/*
======================================================
CREATE DATABASE AND SCHEMAS
======================================================
SCRIPT PURPOSE:
	THIS SCRIPT CREATES A NEW DATABASE NAMED 'DATAWAREHOUSE' AFTER CHECHING IF IT EXISTS.
	AND IT ALSO SETS UP THREE SCHEMAS WITHIN THE DATABASE: BRONZE, SILVER , AND GOLD.
*/
USE MASTER;
GO

--CREATE THE 'DATAWAREHOUSE' DATABASE AFTER CHECKING IF IT EXISTS
IF NOT EXISTS(
	SELECT NAME
	FROM SYS.DATABASES
	WHERE NAME = N'Datawarehouse'
)
BEGIN 
	CREATE DATABASE Datawarehouse;
END;
GO

USE DataWarehouse;
GO

--CREATE SCHEMAS
CREATE SCHEMA BRONZE;
GO

CREATE SCHEMA SILVER;
GO

CREATE SCHEMA GOLD;
GO


